name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
#     - name: Clear repository
#       run: sudo rm -fr $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE
      
    - uses: actions/checkout@v3
      with:
          credentials: ${{ secrets.ROOT_SECRET}}
#     - name: Set up JDK 11
#       uses: actions/setup-java@v3
#       with:
#         java-version: '11'
#         distribution: 'temurin'
#         cache: maven
    - name: Maven-Build     
      run:
         ./maveninstall.sh
#        ls target
      #run: ./mavenisntall.sh
#     - name: Build with Maven
#       run: mvn -B package 
#     - name: Download a Build Artifact
#       uses: actions/download-artifact@v2.1.1
#       with:
#     # Artifact name
#         name: mvn-build-artifact
#     # Destination path
#         path: target/studentapp-2.2-SNAPSHOT.war.war
    
  Build-docer-image:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Building Docker Image

      run:  
        ls
        pwd
        
       # sudo docker build -t omkarphadtare321/java-tom .  # Build docker image frm dockerfile
       # sudo docker run -itd -p 8080:8080  --name java-project omkarphadtare321/java-tom  #create container using docker image 
       # sudo docker ps 
   
